"use client";

import { jsPDF } from "jspdf";
import { Will, Profile } from "@/lib/types";

interface ExportWillButtonProps {
  profile: Profile;
  wills: Will[];
}

export function ExportWillButton({ profile, wills }: ExportWillButtonProps) {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let yPos = 20;

    // Helper function to add text with word wrap
    const addWrappedText = (text: string, fontSize: number, isBold = false) => {
      doc.setFontSize(fontSize);
      doc.setFont("helvetica", isBold ? "bold" : "normal");
      const lines = doc.splitTextToSize(text, contentWidth);
      doc.text(lines, margin, yPos);
      yPos += lines.length * (fontSize * 0.4) + 4;
    };

    // Helper to check for page break
    const checkPageBreak = (neededSpace: number) => {
      if (yPos + neededSpace > doc.internal.pageSize.getHeight() - 40) {
        doc.addPage();
        yPos = 20;
      }
    };

    // Title
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("LAST WILL AND TESTAMENT", pageWidth / 2, yPos, { align: "center" });
    yPos += 15;

    // Subtitle
    doc.setFontSize(12);
    doc.setFont("helvetica", "italic");
    doc.text("(Digital Assets & Personal Property)", pageWidth / 2, yPos, { align: "center" });
    yPos += 20;

    // Legal disclaimer
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const disclaimer = `IMPORTANT LEGAL NOTICE: This document is generated by Iwill (gotwilled.com) for personal record-keeping and entertainment purposes only. This document is NOT a legally binding will and does not replace a formal last will and testament prepared in accordance with applicable state or local laws. For legally binding estate planning, please consult with a licensed attorney in your jurisdiction. By signing below, you acknowledge that this document represents your informal wishes regarding the distribution of the listed items and is not intended to have legal effect.`;
    const disclaimerLines = doc.splitTextToSize(disclaimer, contentWidth);
    doc.text(disclaimerLines, margin, yPos);
    yPos += disclaimerLines.length * 4 + 10;

    // Horizontal line
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    // Declaration
    const displayName = profile.display_name || profile.username;
    const today = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    addWrappedText(`I, ${displayName} (@${profile.username}), being of sound mind and memory, do hereby declare this to be an expression of my wishes regarding the distribution of the following personal property and digital assets upon my passing:`, 11, false);
    yPos += 10;

    // Items section
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("BEQUESTS", margin, yPos);
    yPos += 10;

    if (wills.length === 0) {
      doc.setFontSize(11);
      doc.setFont("helvetica", "italic");
      doc.text("No items have been willed yet.", margin, yPos);
      yPos += 15;
    } else {
      wills.forEach((will, index) => {
        checkPageBreak(25);

        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        const recipientName = will.recipient?.display_name ||
                              will.recipient?.username ||
                              will.recipient_email ||
                              "Unspecified recipient";

        doc.text(`${index + 1}. ${will.item_description}`, margin, yPos);
        yPos += 6;

        doc.setFont("helvetica", "normal");
        doc.text(`    To: ${recipientName}`, margin, yPos);
        yPos += 5;

        const statusText = will.status === "accepted" ? "(Accepted)" :
                          will.status === "declined" ? "(Declined)" :
                          "(Pending acceptance)";
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        doc.text(`    Status: ${statusText}`, margin, yPos);
        yPos += 10;
      });
    }

    // Executor section (if they have one set)
    if (profile.executor_email) {
      checkPageBreak(30);
      yPos += 5;
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("EXECUTOR", margin, yPos);
      yPos += 8;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const executorText = `I hereby designate ${profile.executor_email} as the executor of this informal will, to ensure my wishes regarding the above items are communicated to the intended recipients.`;
      const executorLines = doc.splitTextToSize(executorText, contentWidth);
      doc.text(executorLines, margin, yPos);
      yPos += executorLines.length * 5 + 10;
    }

    // Signature section
    checkPageBreak(80);
    yPos += 10;
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 15;

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("SIGNATURE", margin, yPos);
    yPos += 15;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("I affirm that the above represents my wishes as of the date signed below.", margin, yPos);
    yPos += 20;

    // Signature line
    doc.text("Signature: ", margin, yPos);
    doc.line(margin + 25, yPos, margin + 120, yPos);
    yPos += 15;

    // Printed name line
    doc.text("Printed Name: ", margin, yPos);
    doc.line(margin + 35, yPos, margin + 120, yPos);
    yPos += 15;

    // Date line
    doc.text("Date: ", margin, yPos);
    doc.line(margin + 15, yPos, margin + 80, yPos);
    yPos += 20;

    // Witness section
    checkPageBreak(50);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("WITNESS (Optional)", margin, yPos);
    yPos += 12;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Witness Signature: ", margin, yPos);
    doc.line(margin + 45, yPos, margin + 120, yPos);
    yPos += 12;

    doc.text("Printed Name: ", margin, yPos);
    doc.line(margin + 35, yPos, margin + 120, yPos);
    yPos += 12;

    doc.text("Date: ", margin, yPos);
    doc.line(margin + 15, yPos, margin + 80, yPos);
    yPos += 20;

    // Footer
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text(`Generated by Iwill (gotwilled.com) on ${today}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 15, { align: "center" });

    // Save the PDF
    const fileName = `${profile.username}-will-${new Date().toISOString().split("T")[0]}.pdf`;
    doc.save(fileName);
  };

  return (
    <button
      onClick={generatePDF}
      className="px-4 py-1.5 border border-[var(--card-border)] rounded-full text-sm hover:bg-white/5 transition flex items-center gap-2"
    >
      <span>📄</span>
      <span>Export Will</span>
    </button>
  );
}
